language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t navrisham1/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true navrisham1/docker-frontend npm run test


deploy:
  provider: heroku
  app: docker-front-end
  api_key:
    secure: $TOKEN
