# use an existing docker image as a base
FROM node:alpine

WORKDIR /app

# download and install dependency
COPY ./package.json ./
RUN npm install
COPY ./ ./
# tell image what to do when it start as container

CMD ["npm", "run", "start"]
